version: '3'
services:
  db:
    image: mysql:latest
    container_name: exam-mysql-db
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_USER: user 
      MYSQL_PASSWORD: user-password # DON'T USE IN PRODUCTION
      MYSQL_ROOT_PASSWORD: root-password # DON'T USE IN PRODUCTION
      MYSQL_DATABASE: exam
    ports:
      - 3306:3306
    volumes: # saves the db locally so it's persistent 
       - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: exam-phpmyadmin
    links:
      - db
    environment: # defines the info to access the db as defined above
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: user-password
      PMA_ARBITRARY: 1
#    restart: always
    ports:
      - 2000:80
  
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes: # the study we want django to run 
      - ./django:/django
    depends_on: # the db used for storing as defined above
      - db
    ports:
      - 8000:80

  node:
    image: node:16
    working_dir: /usr/src/app
    restart: always
    volumes:
       - ./gwusec-survey-tech:/usr/src/app
    ports:
      - 80:80
    command: [ "node", "server.js" ]
